### ISSUE TITLE
Invalid Literal

### ISSUE THREAD

**Issue by pawalt** [carosio/bird-snmp-agent#1]
I'm trying to use observium to see all the bgp data on bird. I've got snmp all configured on the bird side, but there's something up with the bgp polling. When I poll for bgp, I get this error:

`Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/opt/bird-snmp-agent/adv_agentx.py", line 372, in _handler_wrapper
    AXObject.GlobalsRun('OnUpdate')
  File "/opt/bird-snmp-agent/adv_agentx.py", line 609, in GlobalsRun
    self.Globals[name](self, self.AXData)
  File "./bird_bgp.py", line 78, in <lambda>
    "OnUpdate"      : lambda ax, axd: OnUpdate(ax,axd,bird.getBGPState())
  File "/opt/bird-snmp-agent/birdagent.py", line 237, in getBGPState
    timestamp = int(match.group(2))
ValueError: invalid literal for int() with base 10: '16:20:16'`

Any idea what might be going on?

**Comment by pawalt** [comment]
Nevermind I had to add this to the top of bird.conf:
`timeformat protocol "%s";`
