### ISSUE TITLE
ctypes.ArgumentError: argument 2: <type 'exceptions.TypeError'>: wrong type

### ISSUE THREAD

**Issue by seeker-dsr** [carosio/bird-snmp-agent#5]
Got this error on every librenms discover. 
```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/etc/bird-snmp-agent/adv_agentx.py", line 404, in _handler_wrapper
    req.SetValue(AXObject.AXData[req.oid]['value'])
  File "/etc/bird-snmp-agent/adv_agentx.py", line 349, in SetValue
    axl.snmp_set_var_typed_value(self.__request.requestvb, otype, ctypes.cast(value, ctypes.POINTER(ctypes.c_ubyte)), size)
ctypes.ArgumentError: argument 2: <type 'exceptions.TypeError'>: wrong type
```
CentOS Linux release 7.5.1804 (Core) 
BIRD version 1.6.3

**Comment by traderose** [comment]
same here, everytime librenms discover:

`Dec 18 19:10:14 pav-rr-01 bird_bgp.py[2433]:   File "/etc/bird/bird-snmp-agent/adv_agentx.py", line 349, in SetValue
Dec 18 19:10:14 pav-rr-01 bird_bgp.py[2433]:     axl.snmp_set_var_typed_value(self.__request.requestvb, otype, ctypes.cast(value, ctypes.POIN
Dec 18 19:10:14 pav-rr-01 bird_bgp.py[2433]: ctypes.ArgumentError: argument 2: <type 'exceptions.TypeError'>: wrong type
Dec 18 19:10:15 pav-rr-01 bird_bgp.py[2433]: Traceback (most recent call last):
Dec 18 19:10:15 pav-rr-01 bird_bgp.py[2433]:   File "_ctypes/callbacks.c", line 315, in 'calling callback function'
Dec 18 19:10:15 pav-rr-01 bird_bgp.py[2433]:   File "/etc/bird/bird-snmp-agent/adv_agentx.py", line 404, in _handler_wrapper
Dec 18 19:10:15 pav-rr-01 bird_bgp.py[2433]:     req.SetValue(AXObject.AXData[req.oid]['value'])
Dec 18 19:10:15 pav-rr-01 bird_bgp.py[2433]:   File "/etc/bird/bird-snmp-agent/adv_agentx.py", line 349, in SetValue
Dec 18 19:10:15 pav-rr-01 bird_bgp.py[2433]:     axl.snmp_set_var_typed_value(self.__request.requestvb, otype, ctypes.cast(value, ctypes.POIN
Dec 18 19:10:15 pav-rr-01 bird_bgp.py[2433]: ctypes.ArgumentError: argument 2: <type 'exceptions.TypeError'>: wrong type
`

also the snmpd service shows the following error:

`Dec 18 19:10:32 pav-rr-01 snmpd[1253]:     -- iso.3.6.1.2.1.15.2
Dec 18 19:10:32 pav-rr-01 snmpd[1253]:     -- iso.3.6.1.2.1.15.2
Dec 18 19:10:33 pav-rr-01 snmpd[1253]: Connection from UDP: [165.16.208.135]:41315->[10.2.4.254]:161
Dec 18 19:10:33 pav-rr-01 snmpd[1253]: snmp_build: unknown failure
Dec 18 19:10:33 pav-rr-01 snmpd[1253]: send response: Error building ASN.1 representation (wrong type in snmp_realloc_rbuild_var_op: 199)
Dec 18 19:10:33 pav-rr-01 snmpd[1253]:     -- iso.3.6.1.2.1.15.2
Dec 18 19:10:33 pav-rr-01 snmpd[1253]:     -- iso.3.6.1.2.1.15.2
Dec 18 19:10:33 pav-rr-01 snmpd[1253]:     -- iso.3.6.1.2.1.15.2
Dec 18 19:10:34 pav-rr-01 snmpd[1253]: Connection from UDP: [165.16.208.135]:55747->[10.2.4.254]:161
Dec 18 19:10:34 pav-rr-01 snmpd[1253]: Connection from UDP: [165.16.208.135]:55747->[10.2.4.254]:161
`

**Comment by traderose** [comment]
same here, everytime librenms discover:

--
   File "/etc/bird/bird-snmp-agent/adv_agentx.py", line 349, in SetValue
     axl.snmp_set_var_typed_value(self.__request.requestvb, otype, ctypes.cast(value, ctypes.POIN
 ctypes.ArgumentError: argument 2: <type 'exceptions.TypeError'>: wrong type
 Traceback (most recent call last):
   File "_ctypes/callbacks.c", line 315, in 'calling callback function'
   File "/etc/bird/bird-snmp-agent/adv_agentx.py", line 404, in _handler_wrapper
     req.SetValue(AXObject.AXData[req.oid]['value'])
   File "/etc/bird/bird-snmp-agent/adv_agentx.py", line 349, in SetValue
     axl.snmp_set_var_typed_value(self.__request.requestvb, otype, ctypes.cast(value, ctypes.POIN
 ctypes.ArgumentError: argument 2: <type 'exceptions.TypeError'>: wrong type


also the snmpd service shows the following error:

 Connection from UDP: [librenms_ip]:41315->[bird_ip]:161
 snmp_build: unknown failure
 send response: Error building ASN.1 representation (wrong type in snmp_realloc_rbuild_var_op: 199)
     -- iso.3.6.1.2.1.15.2
     -- iso.3.6.1.2.1.15.2
     -- iso.3.6.1.2.1.15.2
 Connection from UDP: [librenms_ip]:55747->[bird_ip]:161
 Connection from UDP: [librenms_ip]:55747->[bird_ip]:161
